### ISSUE TITLE
Tomcat 7.0.42 putALL deadlock 

### ISSUE THREAD

**Issue by heiducteam** [jsr107/RI#58] opened 2017-09-11 10:20 UTC
at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000786988248> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at org.jsr107.ri.LockManager$LockFactory.getLock(LockManager.java:91)
	at org.jsr107.ri.LockManager$LockFactory.access$100(LockManager.java:75)
	at org.jsr107.ri.LockManager.lock(LockManager.java:47)
	at org.jsr107.ri.RICache.putAll(RICache.java:799)
	at org.jsr107.ri.RICache.putAll(RICache.java:754)
	at org.jsr107.ri.RICache.putAll(RICache.java:747)

**Comment by cruftex** [comment] 2017-10-07 11:28
The problem is that `putAll()` makes a bulk lock on all keys, does the processing and then unlocks. Because of the random order of the bulk lock, this is prone to a deadlock.

The JSR107 RI isn't really vetted for proper concurrent behavior and should not be used in production as you do. Fixing this bug makes no difference.

**Comment by vbekiaris** [comment] 2017-10-07 17:34
Closing this issue as RI is not meant for production use.

**Closed by vbekiaris** 2017-10-07 17:34 UTC
